INSERT INTO USERDETAILS(USER_NAME,PASSWORD) VALUES('admin1','password1');
INSERT INTO USERDETAILS(USER_NAME,PASSWORD) VALUES('admin2','password2');
INSERT INTO USERDETAILS(USER_NAME,PASSWORD) VALUES('admin3','password3');